### ISSUE TITLE
Dependabot Spring Framework upgrade has broken the build!

### ISSUE THREAD

**Issue by muammeryucel** [AxonFramework/extension-kafka#91] opened 2020-12-13 16:09 UTC
Downgrading to version 5.3.1 fixes the build.

**Comment by muammeryucel** [comment] 2020-12-13 18:03
IMHO Spring version should be decided by Spring Boot and Spring Kafka. It shouldn't be clearly declared. For the axon-kafka module, it should be managed by spring-kafka. For autoconfigure module, it should be managed by Spring Boot. In addition, axon-kafka-example shouldn't be inherited from axon-kafka-parent. It should be inherited from spring-boot-starter-parent, because it exemplifies the use of the axon-kafka module and will mostly be used that way. I think, no one will ever use the axon-kafka-parent as a parent pom.

**Comment by smcvb** [comment] 2020-12-14 10:59
Arguably not a bug if you ask me, but still something we can indeed improve on. I've adjust the labels accordingly and attached @sandjelkovic as he's working on adjusting this behavior. As always, thank you so much for the insights here @muammeryucel. Any and all help is always very much appreciated. :+1:

**Comment by muammeryucel** [comment] 2020-12-14 19:13
I totally agree with you @smcvb. It isn't a bug, you are right. I shouldn't have opened the ticket with predefined issue templates. Sorry.

**Comment by sandjelkovic** [comment] 2021-01-29 10:43
As the core of this issue were compilation issues caused by dependency incompatibility, which was resolved in https://github.com/AxonFramework/extension-kafka/pull/96 I would consider this issue resolved. While the CI build is still not entirely fixed, the tests can be now run locally and the reasons for current CI failures are entirely different. I created https://github.com/AxonFramework/extension-kafka/issues/108 to track this improvement and CI fix as a separate issue and PR.

**Closed by sandjelkovic** 2021-01-29 10:43 UTC
Labels: Priority 2: Should, Status: In Progress, Type: Dependency Upgrade
