### ISSUE TITLE
KafkaPublisher should track events instead of subscribing on them

### ISSUE THREAD

**Issue by a-hegerath** [AxonFramework/extension-kafka#10] opened 2019-09-02 12:13 UTC
The `KafkaPublisher` uses a `SubscribableMessageSource` to subscribe on events and send them to a configured Kafka topic. Since sending is not re-tried upon failure, events may get "lost".
A reliably approach could be to use a `StreamableMessageSource` instead, to have event _tracking_ (rather than event _subscription_) semantics. The tracking token would be incremented on successful sending only (in transactional mode: when tx is commited, in ack mode: when publish is acknowledged).

This relates to [this discussion](https://groups.google.com/d/msg/axonframework/BvjhuV6r2dM/dNsIf4WAAgAJ).

**Comment by abuijze** [comment] 2019-09-02 13:33
Hi @a-hegerath,

the reason that the KafkaPublisher uses a `SubscribableMessageSource` rather than a Streamable one, is because the publication of Events to Kafka was intended to be part of the publishing transaction. With a Streamable one, that's no longer the case.

The flow would be:
1. Command arrives
2. Transaction started
3. Command handler invoked, Events staged for publication
4. Command handling completes, Unit of Work starts Commit
5. Events sent to AxonServer / Event Store
6. Subscribable messages sources provided with Events
7. Transactions committed
8. Unit of Work commit completed / resource cleanup

So if step 6 fails, there is a possibility to raise an error and force the Unit of Work to be rolled back.

**Comment by a-hegerath** [comment] 2019-09-02 14:28
Hi @abuijze ,

thanks for pointing this out. I admit that the current implementation _is_ reliable given that command handling and event sending is part of the same transaction.

Our use case is different though. In our application it shall be possible to handle commands (and thus modify application state) even while event transmission over Kafka is not possible. This seems to be possible in a realiable way only with event tracking.

Do you see any way of unifying both approaches in the implementation, so that it is possible to chose by configuration with one to take? This seems hard to me since event subscription and event tracking are fundamentally different concepts of how to process events.

**Comment by zambrovski** [comment] 2019-09-17 16:05
I'll try to provide an implementation for that.

**Comment by zambrovski** [comment] 2019-09-18 13:15
Using the implementation you can now support the following flow in addition to that one, defined by https://github.com/AxonFramework/extension-kafka/issues/10#issuecomment-527150083

1. Command arrives
2. Transaction started
3. Command handler invoked, Events staged for publication
4. Command handling completes, Unit of Work starts Commit
5. Events sent to AxonServer / Event Store
6. Transactions committed
7. Unit of Work commit completed / resource cleanup

8. Transaction started
9. The Tracking processor detects the change via token
10. Event is delivered to Kafka publisher
11. Transactions committed

If the error happens somewhere between 1. and 7. the transaction will not be committed and 
command is not handled successfully. If it is indeed and an error happens between 8. and 11. the 
event processor will go into tracking mode and retry. 

So if the core part of your application (aggregates and command handlers) accept an atomic
inconsistency but rely on eventual consistency, the tracking mode can help you to achieve this. This is specifically interesting in case if the core of the application doesn't accept failures resulting from infrastructure failures (like a Kafka problem).

**Closed** 2019-10-08 12:28 UTC
Labels: Priority 2: Should, Status: In Progress, Status: Under Discussion, Type: Feature
