### ISSUE TITLE
Outdated tracking token used upon Kafka partition assignment

### ISSUE THREAD

**Issue by a-hegerath** [AxonFramework/extension-kafka#25] opened 2019-12-05 14:25 UTC
We are using the Kafka extension in our application to deliver Axon events over Kafka. Recently, we encountered an event loss after the Kafka broker was temporarily not available for the consumer. Since we found the event in the Kafka topic, we assumed that the event got lost on consumer side.
After diving somewhat into the code of the Kafka extension, I guess that I have spotted the problem:

In class `org.axonframework.extensions.kafka.eventhandling.consumer.ConsumerUtil`, the `seek` method subscribes to records of the given topic. Also, a `ConsumerRebalanceListener` is registered, which, on partition assignment, seeks for each partition to the proper offset, using a given Kafka tracking token. The issue is that **this particular token is used for each future partition assignment**, too. This has one of the following two consequences:

- If the offset does not exist any more, because the Kafka cluster is set up to maintain the records only for a limited amount of time, then the offset is reset. The default reset strategy 'LATEST' may cause event loss because records may be skipped (this is what happened in our case).
- If the offset does exist, all events since the initial partition assignment are replayed. This is not necessarily an error, but likely not what applications would expect.

To my mind, the above mentioned `seek` method should not be given a token, but rather a token supplier/provider, so that upon partition assignment, the most recent token could be used. What do you think? If you agreed, I'd be up for providing a PR. If not, do you have any suggestions how to get around the issue that we faced?

Thanks and regards,
Andre

**Comment by smcvb** [comment] 2019-12-12 11:31
Thanks for filing this concern with us @a-hegerath. As it stands, I was just starting to work on #18, which imposes adjustments to the `ConsumerUtil` class, but more specifically how the `ConsumerRebalanceListener` behaves.

As you can read from issue #18, we will enforce the offset to be zero for unknown partitions. This thought is in line with how Axon deals with empty / non-existent `TrackingTokens`, hence we feel this should be enforced at all times when the streamable approach of the Kafka Extension is utilized. I will ensure this is correctly documented in our reference guide, to overcome the second bullet point you've provided.

What you changed in my approach for this new `ConsumerRebalanceListener`, is introducing a `Supplier<KafkaTrackingToken>` to be used by the listener. This is indeed a hard requirement to ensure the most recent state of the record consumption is taken into consideration for the `Consume#seek(TopicPartition, long)` operation.

A PR for #18 will follow soon, which will also cover this bug you've reported.

**Comment by smcvb** [comment] 2019-12-12 12:38
As said, the problem is being addressed in #27. Feel free to take a look @a-hegerath, I'd want to know whether you feel this will resolve the problem you've encountered too.

And again, thanks for filing this concern with us!

**Comment by smcvb** [comment] 2019-12-12 14:54
Closing as this issue has been resolved in pull request #27

**Closed by smcvb** 2019-12-12 14:54 UTC
Labels: Priority 1: Must, Status: Resolved, Type: Bug

**Comment by a-hegerath** [comment] 2019-12-12 16:00
Hi Steven,

the changes look very reasonable to me. Until a new release of axon-kafka is available, we'll build a version ourselves which include your changes. We'll let you know if we still observe an event loss as described also with that version.

Thanks,
Andre

**Comment by smcvb** [comment] 2019-12-13 10:24
I am very happy to hear that Andre!
A release will come shortly, promised.
So stay tuned for that. :-)
